name: Build and Deploy to GKE

on:
  [push]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: gke    # Add your cluster name here.
  GKE_ZONE: asia-southeast1   # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2


    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Init setup
      run: |-
        echo $GKE_SA_KEY > .gcloud-api-key.json
        docker login -u _json_key --password-stdin https://gcr.io < .gcloud-api-key.json
        gcloud auth activate-service-account --key-file .gcloud-api-key.json
        gcloud container clusters get-credentials $GKE_CLUSTER --region=$GKE_ZONE --project $PROJECT_ID


    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        cd k8s/
        kubectl apply -f .